export const Questions =[
    {
        prompt:'台灣首都在哪?',
        optionA:'台中',
        optionB:'台北',
        optionC:'首爾',
        optionD:'高雄',
        answer:'B'
    },
    {
        prompt:'台灣最高山為哪座山?',
        optionA:'玉山',
        optionB:'陽明山',
        optionC:'阿里山',
        optionD:'富士山',
        answer:'A'
    },
    {
        prompt:'台灣沒有以下哪個天災?',
        optionA:'地震',
        optionB:'颱風',
        optionC:'乾旱',
        optionD:'火山爆發',
        answer:'D'
    },
]